# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('OH', 'On Hold'), ('CO', 'Complete')], max_length=2)),
                ('position', models.CharField(max_length=255)),
                ('applied_date', models.DateField(null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JQ.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('ceo', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('incorporated', models.CharField(blank=True, max_length=4)),
                ('other_notes', models.TextField(blank=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('isDeleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JQ.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('note_date', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('App', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JQ.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=25)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('LI', 'Linkedin'), ('WS', 'Website'), ('GD', 'Glassdoor'), ('OT', 'Other')], max_length=2)),
                ('isDeleted', models.BooleanField(default=False)),
                ('App', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JQ.Application')),
            ],
        ),
        migrations.AddField(
            model_name='ask',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JQ.Questions'),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JQ.Company'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
