# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQ', '0003_auto_20170826_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
