# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JQ', '0004_resources_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='App',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JQ.Application'),
        ),
    ]
