# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JQ', '0005_questions_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='App',
        ),
    ]
