# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JQ', '0006_remove_questions_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
