# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQ', '0008_auto_20171128_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
