# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(blank=True, max_length=255)),
                ('Short_list', models.BooleanField(default=False)),
                ('Status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('OH', 'On Hold'), ('CO', 'Complete')], max_length=2)),
                ('Start_Date', models.DateField(auto_now_add=True)),
                ('Modified_Date', models.DateField(auto_now=True)),
                ('Goal_Date', models.DateField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('Complete_Date', models.DateField(blank=True, null=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
