# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem', to=settings.AUTH_USER_MODEL)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own', to=settings.AUTH_USER_MODEL)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project')),
            ],
        ),
    ]
