# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180223_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='count_tasks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percent_complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percent_overdue',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.Project'),
        ),
    ]
