# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_projectmember'),
    ]

    operations = [

        migrations.AlterField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.Project'),
        ),
    ]
